version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - '.dev.env'
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
    command: pnpm run start:dev
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  minio:
    container_name: minio
    image: docker.io/bitnami/minio:2022
    env_file:
      - '.dev.env'
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    ports:
      - '${MINIO_API_PORT}:${MINIO_API_PORT}'
      - '${MINIO_UI_PORT}:${MINIO_UI_PORT}'
    command: 'minio server --console-address ":${MINIO_API_PORT}" /data'
    volumes:
      - 'minio:/data'

volumes:
  mysqldb:
  redis:
  minio:
    driver: local
