export const SEQUELIZE = 'SEQUELIZE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const SHELTER_REPOSITORY = 'SHELTER_REPOSITORY';
export const ANIMAL_REPOSITORY = 'ANIMAL_REPOSITORY';
export const PHOTO_REPOSITORY = 'PHOTO_REPOSITORY';
export const CHAT_REPOSITORY = 'CHAT_REPOSITORY';
export const MESSAGE_REPOSITORY = 'MESSAGE_REPOSITORY';
export const POST_REPOSITORY = 'POST_REPOSITORY';
